import address from 'address';
import chalk from 'chalk';
import cheerio from 'cheerio';
import spawn from 'cross-spawn';
import chokidar from 'chokidar';
import clipboardy from 'clipboardy';
import createDebug, { Debugger } from 'debug';
import deepmerge from 'deepmerge';
import execa from 'execa';
import lodash from 'lodash';
import glob from 'glob';
import portfinder from 'portfinder';
import got from 'got';
import resolve from 'resolve';
import yargs from 'yargs';
import mkdirp from 'mkdirp';
import mustache from 'mustache';
import signale from 'signale';
import rimraf from 'rimraf';
import yParser from 'yargs-parser';
import semver from 'semver';

export { address };
export { chalk };
export { cheerio };
export { spawn };
export { chokidar };
export { clipboardy };
export { createDebug, Debugger };
export { deepmerge };
export { execa };
export { lodash };
export { glob };
export { portfinder };
export { got };
export { resolve };
export { yargs };
export { mkdirp };
export { mustache };
export { signale };
export { rimraf };
export { yParser };
export { semver };

export { default as BabelRegister } from './babel-register';
export { default as compatESModuleRequire } from './compat-esmodule-require';
export { default as delay } from './delay';
export { default as generator } from './generator';
export { default as getFile } from './get-file';
export { default as isLernaPackage } from './is-lerna-package';
export { default as mergeConfig } from './merge-config';
export { default as parseRequireDeps } from './parse-require-deps';
export { default as randomColor } from './random-color';
export { default as winPath } from './win-path';
export { default as winEOL } from './win-eol';

export * from './types';
